Update font installation script with custom and maple fonts
- Replace rsync with find and cp for more robust font installation
- Use extended regular expressions for flexible font file matching
- Add support for Maple Mono custom builds from GitHub releases
- Add support for custom fonts stored in the fonts branch
- Switch JetBrains Mono to use variable font versions

diff --git a/.chezmoiscripts/run_onchange_after_99-install-fonts.sh.tmpl b/.chezmoiscripts/run_onchange_after_99-install-fonts.sh.tmpl
--- a/.chezmoiscripts/run_onchange_after_99-install-fonts.sh.tmpl
+++ b/.chezmoiscripts/run_onchange_after_99-install-fonts.sh.tmpl
@@ -8,7 +8,7 @@ set -euo pipefail
 install_font() {
   local font_name="$1"
   local url="$2"
-  local font_glob="$3"
+  local file_regex="$3"
   local temp_dir
   temp_dir=$(mktemp -d)
 
@@ -28,26 +28,44 @@ install_font() {
     return 1
   fi
 
-  # Copy the fonts to /Library/Fonts using rsync
-  if sudo rsync -av --include="${font_glob}" --exclude="*" "${temp_dir}/" /Library/Fonts/ >/dev/null; then
-    log_success "${font_name} installed successfully"
-  else
-    log_error "Failed to install ${font_name} to /Library/Fonts"
+  # Find matching font files using extended regex
+  local font_files
+  font_files=$(find -E "${temp_dir}" -type f -regex "${file_regex}")
+
+  if [[ -z "${font_files}" ]]; then
+    log_error "No font files matching '${file_regex}' found in ${font_name} archive"
     rm -rf "${temp_dir}"
     return 1
   fi
 
+  local copy_failed=false
+  while IFS= read -r font_file; do
+    local filename
+    filename=$(basename "${font_file}")
+    if ! sudo cp "${font_file}" "/Library/Fonts/${filename}"; then
+      log_error "Failed to copy ${filename} to /Library/Fonts"
+      copy_failed=true
+    fi
+  done <<< "${font_files}"
+
   # Clean up
   rm -rf "${temp_dir}"
+
+  if [[ "${copy_failed}" == "true" ]]; then
+    log_error "Failed to install some fonts from ${font_name}"
+    return 1
+  fi
+
+  log_success "${font_name} installed successfully"
   return 0
 }
 
 install_all_fonts() {
   local failed_fonts=()
 
-  # JetBrains Mono
+  # JetBrains Mono (variable fonts)
   local jb_mono_url='{{ gitHubLatestReleaseAssetURL "JetBrains/JetBrainsMono" "JetBrainsMono-*.zip" }}'
-  install_font "JetBrains Mono" "${jb_mono_url}" 'fonts/ttf/*.ttf'
+  install_font "JetBrains Mono" "${jb_mono_url}" '.*/fonts/variable/.*\.ttf'
   local exit_code=$?
   if [[ ${exit_code} -ne 0 ]]; then
     failed_fonts+=("JetBrains Mono")
@@ -55,7 +73,7 @@ install_all_fonts() {
 
   # Source Han Sans
   local shs_url='{{ gitHubLatestReleaseAssetURL "adobe-fonts/source-han-sans" "*SourceHanSans.ttc.zip" }}'
-  install_font "Source Han Sans" "${shs_url}" '*.ttc'
+  install_font "Source Han Sans" "${shs_url}" '.*\.ttc'
   exit_code=$?
   if [[ ${exit_code} -ne 0 ]]; then
     failed_fonts+=("Source Han Sans")
@@ -63,10 +81,26 @@ install_all_fonts() {
 
   # Nerd Fonts - JetBrains Mono
   local nf_jb_mono_url='{{ gitHubLatestReleaseAssetURL "ryanoasis/nerd-fonts" "JetBrainsMono.zip" }}'
-  install_font "Nerd Fonts JetBrains Mono" "${nf_jb_mono_url}" '*.ttf'
+  install_font "Nerd Fonts JetBrains Mono" "${nf_jb_mono_url}" '.*\.ttf'
   exit_code=$?
   if [[ ${exit_code} -ne 0 ]]; then
     failed_fonts+=("Nerd Fonts JetBrains Mono")
+  fi
+
+  # Maple Mono MuXiu1997
+  local maple_mono_url='{{ gitHubLatestReleaseAssetURL "MuXiu1997/maple-font-custom" "*-NF-CN-*.zip" }}'
+  install_font "Maple Mono MuXiu1997" "${maple_mono_url}" '.*\.ttf'
+  exit_code=$?
+  if [[ ${exit_code} -ne 0 ]]; then
+    failed_fonts+=("Maple Mono MuXiu1997")
+  fi
+
+  # Custom Fonts from fonts branch
+  local custom_fonts_url="https://github.com/MuXiu1997/dotfiles/archive/fonts.zip"
+  install_font "Custom Fonts" "${custom_fonts_url}" '.*\.(otf|ttf|TTF)'
+  exit_code=$?
+  if [[ ${exit_code} -ne 0 ]]; then
+    failed_fonts+=("Custom Fonts")
   fi
 
   # Report results
