Optimize shell scripts formatting and configuration

diff --git a/.chezmoiscripts/run_once_before_00-install-required-packages.sh.tmpl b/.chezmoiscripts/run_once_before_00-install-required-packages.sh.tmpl
--- a/.chezmoiscripts/run_once_before_00-install-required-packages.sh.tmpl
+++ b/.chezmoiscripts/run_once_before_00-install-required-packages.sh.tmpl
@@ -1,34 +1,35 @@
 #!/usr/bin/env bash
-set -eufo pipefail
+
+set -euo pipefail
 
 install_homebrew() {
-    if ! type brew &>/dev/null; then
-        echo "Installing Homebrew..."
-        bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
-        echo "Homebrew installation completed"
-    else
-        echo "Homebrew is already installed"
-    fi
+  if ! type brew &>/dev/null; then
+    echo "Installing Homebrew..."
+    NONINTERACTIVE=1 bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+    echo "Homebrew installation completed"
+  else
+    echo "Homebrew is already installed"
+  fi
 }
 
 install_required_packages() {
-    echo "Installing required packages..."
-    local packages=("git" "age" "chezmoi")
-    
-    for package in "${packages[@]}"; do
-        if ! brew list --versions "$package" &>/dev/null; then
-            echo "Installing $package..."
-            {{ .homebrewExec }} install "$package"
-        else
-            echo "$package is already installed"
-        fi
-    done
-    echo "All required packages installed"
+  echo "Installing required packages..."
+  local packages=("git" "age" "chezmoi")
+
+  for package in "${packages[@]}"; do
+    if ! {{ .homebrewExec }} list --versions "$package" &>/dev/null; then
+      echo "Installing $package..."
+      {{ .homebrewExec }} install "$package"
+    else
+      echo "$package is already installed"
+    fi
+  done
+  echo "All required packages installed"
 }
 
 main() {
-    install_homebrew
-    install_required_packages
+  install_homebrew
+  install_required_packages
 }
 
 main
diff --git a/.chezmoiscripts/run_onchange_after_99-install-fonts.sh.tmpl b/.chezmoiscripts/run_onchange_after_99-install-fonts.sh.tmpl
--- a/.chezmoiscripts/run_onchange_after_99-install-fonts.sh.tmpl
+++ b/.chezmoiscripts/run_onchange_after_99-install-fonts.sh.tmpl
@@ -1,22 +1,24 @@
 {{- if (eq .chezmoi.os "darwin") -}}
 #!/usr/bin/env bash
 
+set -euo pipefail
+
 install_fonts() {
-    local url="$1"
-    local font_glob="$2"
-    local temp_dir=$(mktemp -d)
+  local url="$1"
+  local font_glob="$2"
+  local temp_dir=$(mktemp -d)
 
-    # Download the font archive
-    curl -L "$url" -o "$temp_dir/font.zip"
+  # Download the font archive
+  curl -L "$url" -o "$temp_dir/font.zip"
 
-    # Unzip the font archive
-    unzip "$temp_dir/font.zip" -d "$temp_dir"
+  # Unzip the font archive
+  unzip "$temp_dir/font.zip" -d "$temp_dir"
 
-    # Copy the fonts to /Library/Fonts using rsync
-    sudo rsync -av --include="$font_glob" --exclude="*" "$temp_dir/" /Library/Fonts/
+  # Copy the fonts to /Library/Fonts using rsync
+  sudo rsync -av --include="$font_glob" --exclude="*" "$temp_dir/" /Library/Fonts/
 
-    # Clean up
-    rm -rf "$temp_dir"
+  # Clean up
+  rm -rf "$temp_dir"
 }
 
 # JetBrains Mono
@@ -27,4 +29,7 @@ install_fonts {{ gitHubLatestReleaseAssetURL "adobe-fonts/source-han-sans" "Sour
 
 # Nerd Fonts - JetBrains Mono
 install_fonts {{ gitHubLatestReleaseAssetURL "ryanoasis/nerd-fonts" "JetBrainsMono.zip" | squote }} '*.ttf'
+
+# Update font cache
+fc-cache -f
 {{- end }}
