zsh

diff --git a/dot_config/zsh/dot_zshrc b/dot_config/zsh/dot_zshrc
--- a/dot_config/zsh/dot_zshrc
+++ b/dot_config/zsh/dot_zshrc
@@ -5,32 +5,53 @@ if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]
   source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
 fi
 
-# XDG
-# Avoiding overwriting
-export HISTFILE="$XDG_STATE_HOME/zsh/history"
+# { XDG
+    # Avoiding overwriting
+    export HISTFILE="$XDG_STATE_HOME/zsh/history"
+# }
 
-# Oh my zsh
-[[ ! -f "$ZDOTDIR/oh-my-zsh.zsh" ]] || source "$ZDOTDIR/oh-my-zsh.zsh" 
+# { Zsh
+    # Oh my zsh
+    [[ ! -f "$ZDOTDIR/oh-my-zsh.zsh" ]] || source "$ZDOTDIR/oh-my-zsh.zsh" 
 
-# Aliases
-[[ ! -f "$ZDOTDIR/aliases.zsh" ]] || source "$ZDOTDIR/aliases.zsh"
+    # Aliases
+    [[ ! -f "$ZDOTDIR/aliases.zsh" ]] || source "$ZDOTDIR/aliases.zsh"
 
-# Functions
-[[ ! -f "$ZDOTDIR/functions.zsh" ]] || source "$ZDOTDIR/functions.zsh"
+    # Functions
+    [[ ! -f "$ZDOTDIR/functions.zsh" ]] || source "$ZDOTDIR/functions.zsh"
+# }
 
-# Fzf
-zvm_after_init_commands+=("[[ ! -f $XDG_CONFIG_HOME/fzf.zsh ]] || source $XDG_CONFIG_HOME/fzf.zsh") # https://github.com/jeffreytse/zsh-vi-mode#execute-extra-commands
+# { Cli
+    # Zoxide
+    if (( $+commands[zoxide] )); then eval "$(zoxide init zsh)";else echo 'zoxide: command not found, please install it from https://github.com/ajeetdsouza/zoxide'; fi
 
-# Fzf-tab
-zvm_after_init_commands+=("[[ ! -f $XDG_CONFIG_HOME/fzf-tab.zsh ]] || source $XDG_CONFIG_HOME/fzf-tab.zsh")
+    # Fzf
+    zvm_after_init_commands+=("[[ ! -f $XDG_CONFIG_HOME/fzf.zsh ]] || source $XDG_CONFIG_HOME/fzf.zsh") # https://github.com/jeffreytse/zsh-vi-mode#execute-extra-commands
 
-# Iterm2
-[[ ! -f "${HOME}/.iterm2_shell_integration.zsh" ]] || source "${HOME}/.iterm2_shell_integration.zsh"
+    # Fzf-tab
+    zvm_after_init_commands+=("[[ ! -f $XDG_CONFIG_HOME/fzf-tab.zsh ]] || source $XDG_CONFIG_HOME/fzf-tab.zsh")
 
-# Nvm
-# Must be in the .zshrc file
-[ -s "$(brew --prefix)/opt/nvm/nvm.sh" ] && . "$(brew --prefix)/opt/nvm/nvm.sh"
+    # Iterm2
+    [[ ! -f "${HOME}/.iterm2_shell_integration.zsh" ]] || source "${HOME}/.iterm2_shell_integration.zsh"
+# }
 
+# { Nvm
+    # Must be in the .zshrc file
+    # Don't try to load nvm if command already available
+    if ! type nvm &>/dev/null; then
+        [ -s "$(brew --prefix)/opt/nvm/nvm.sh" ] && . "$(brew --prefix)/opt/nvm/nvm.sh"
+    fi
+# }
+
+# { Pyenv
+    if type pyenv &>/dev/null; then
+        eval "$(pyenv init -)"
+    fi
+# }
+
+# { Direnv
+    eval "$(direnv hook zsh)"
+# }
 
 # To customize prompt, run `p10k configure` or edit $ZDOTDIR/.p10k.zsh.
 [[ ! -f "$ZDOTDIR/p10k.zsh" ]] || source "$ZDOTDIR/p10k.zsh"
