Refine direnv configuration formatting

diff --git a/dot_config/direnv/direnvrc b/dot_config/direnv/direnvrc
--- a/dot_config/direnv/direnvrc
+++ b/dot_config/direnv/direnvrc
@@ -1,34 +1,34 @@
 # Function to get the absolute path of a file or directory
 # Example: realpath "path/to/file" => "/absolute/path/to/file"
 realpath() {
-    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
+  [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
 }
 
 # Function to set the version for a given command
 # Example: set_version python 3.8 => sets the version for python to 3.8 (in a file named .python-version)
 set_version() {
-    local command version
-    command="$1"
-    version="$2"
-    if [[ -z "$command" ]]; then
-        log_error "set_version: command is required"
-        exit 1
-    fi
-    if [[ -n "$version" ]]; then
-        echo "$version" > ".$command-version"
-    fi
+  local command version
+  command="$1"
+  version="$2"
+  if [[ -z "$command" ]]; then
+    log_error "set_version: command is required"
+    exit 1
+  fi
+  if [[ -n "$version" ]]; then
+    echo "$version" > ".$command-version"
+  fi
 }
 
 # Function to get the version for a given command
 # Example: get_version python => "3.8" (if set previously in a file named .python-version)
 get_version() {
-    local command version
-    command="$1"
-    if [[ -z "$command" ]]; then
-        log_error "get_version: command is required"
-        exit 1
-    fi
-    head ".$command-version" 2>/dev/null
+  local command version
+  command="$1"
+  if [[ -z "$command" ]]; then
+    log_error "get_version: command is required"
+    exit 1
+  fi
+  head ".$command-version" 2>/dev/null
 }
 
 # Function to log a warning message
@@ -54,48 +54,48 @@ log_warn() {
 #   layout virtualenv "my-venv"
 #   layout virtualenv => layout virtualenv "venv" / layout virtualenv ".venv"
 layout_virtualenv() {
-    local venv_path activate_path has_custom_venv
-    if [[ -n "$1" ]]; then
-        has_custom_venv=true
-        venv_path=$(realpath "$1")
+  local venv_path activate_path has_custom_venv
+  if [[ -n "$1" ]]; then
+    has_custom_venv=true
+    venv_path=$(realpath "$1")
+  else
+    if [[ -d "./venv" ]]; then
+      venv_path=$(realpath "./venv")
+    elif [[ -d "./.venv" ]]; then
+      venv_path=$(realpath "./.venv")
     else
-        if [[ -d "./venv" ]]; then
-            venv_path=$(realpath "./venv")
-        elif [[ -d "./.venv" ]]; then
-            venv_path=$(realpath "./.venv")
-        else
-            log_error "virtualenv: no valid virtualenv path found"
-            exit 1
-        fi
+      log_error "virtualenv: no valid virtualenv path found"
+      exit 1
     fi
+  fi
 
-    activate_path="${venv_path}/bin/activate"
-    if [[ ! -f "$activate_path" ]]; then
-        if [[ "$has_custom_venv" == true ]]; then
-            log_error "virtualenv: no ${activate_path} found"
-            exit 1
-        fi
-        log_warn "virtualenv: $venv_path is not a valid virtualenv path, skip loading"
-        return
+  activate_path="${venv_path}/bin/activate"
+  if [[ ! -f "$activate_path" ]]; then
+    if [[ "$has_custom_venv" == true ]]; then
+      log_error "virtualenv: no ${activate_path} found"
+      exit 1
     fi
-    # shellcheck disable=SC1090
-    source "${activate_path}"
-    # https://github.com/direnv/direnv/wiki/PS1
-    unset PS1
+    log_warn "virtualenv: $venv_path is not a valid virtualenv path, skip loading"
+    return
+  fi
+  # shellcheck disable=SC1090
+  source "${activate_path}"
+  # https://github.com/direnv/direnv/wiki/PS1
+  unset PS1
 }
 
 # Function to activate a Python environment layout using pyenv
 # Example: layout pyenv "3.8.1"
 layout_pyenv() {
-    local python_version
-    set_version python "$1"
-    python_version=$(get_version python)
-    if [[ -z "$python_version" ]]; then
-        log_warn "pyenv: pyenv is used but no python version found, skip loading"
-        return
-    fi
-    pyenv local "$python_version"
-    log_status "pyenv: currently activated python version is $python_version"
+  local python_version
+  set_version python "$1"
+  python_version=$(get_version python)
+  if [[ -z "$python_version" ]]; then
+    log_warn "pyenv: pyenv is used but no python version found, skip loading"
+    return
+  fi
+  pyenv local "$python_version"
+  log_status "pyenv: currently activated python version is $python_version"
 }
 
 # Function to activate Python-related layouts
@@ -103,29 +103,29 @@ layout_pyenv() {
 #   layout python "3.8.1"
 #   layout python "3.8.1" "my-venv"
 layout_python() {
-    layout_pyenv "$1"
-    layout_virtualenv "$2"
+  layout_pyenv "$1"
+  layout_virtualenv "$2"
 }
 
 # Function to activate a Node.js environment layout using fnm
 # Example: layout fnm "18.20.8"
 layout_fnm() {
-    local node_version
-    set_version node "$1"
-    node_version=$(get_version node)
-    if [[ -z "$node_version" ]]; then
-        log_warn "fnm: fnm is used but no node version found, skip loading"
-        return
-    fi
-    fnm use "$node_version"
-    log_status "fnm: currently activated node version is $node_version"
+  local node_version
+  set_version node "$1"
+  node_version=$(get_version node)
+  if [[ -z "$node_version" ]]; then
+    log_warn "fnm: fnm is used but no node version found, skip loading"
+    return
+  fi
+  fnm use "$node_version"
+  log_status "fnm: currently activated node version is $node_version"
 }
 
 # Function to activate Node.js-related layouts
 # Example: layout node "18.20.8"
 layout_node() {
-    PATH_add node_modules/.bin
-    layout_fnm "$1"
+  PATH_add node_modules/.bin
+  layout_fnm "$1"
 }
 
 # Function to activate a Go environment layout using goenv
@@ -135,8 +135,8 @@ layout_goenv() {
   set_version go "$1"
   golang_version=$(get_version go)
   if [[ -z "$golang_version" ]]; then
-        log_warn "goenv: goenv is used but no golang version found, skip loading"
-        return
+    log_warn "goenv: goenv is used but no golang version found, skip loading"
+    return
   fi
   goenv local "$golang_version"
   log_status "goenv: currently activated golang version is $golang_version"
@@ -155,8 +155,8 @@ layout_jenv() {
   set_version java "$1"
   java_version=$(get_version java)
   if [[ -z "$java_version" ]]; then
-        log_warn "jenv: jenv is used but no java version found, skip loading"
-        return
+    log_warn "jenv: jenv is used but no java version found, skip loading"
+    return
   fi
   jenv enable-plugin export >/dev/null 2>&1
   jenv local "$java_version"
